animals = ['bear', 'python', 'peacock', 'kangaroo', 'whale', 'platybus']

print "The animal at 1 is", animals[1]
print "The third (3rd) animal is", animals[2]
print "The first animal is", animals[0]
print "The animal at 3 is", animals[3]
print "The fifth (5th) animal is", animals[4]
print "The animal at 2 is", animals[2]
print "The sixth (6th) animal is", animals[5]
print "The animal at 4 is", animals[4]
